resources:
- name: ruby-image
  type: docker-image
  source:
    repository: registry.hub.docker.com/ministryofjustice/orphaned-namespace-checker
    tag: 1.9
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-30m
  type: time
  source:
    interval: 30m

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

groups:
- name: live-0
  jobs: [check-live-0]

jobs:
- name: check-live-0
  serial: true
  plan:
    - aggregate:
      - get: every-30m
        trigger: true
      - get: ruby-image
    - task: check-environments
      image: ruby-image
      config:
        platform: linux
        params:
          BUCKET_PREFIX: cloud-platform-live-0.k8s.integration.dsd.io
          KUBECONFIG_AWS_ACCESS_KEY_ID: ((aws-live-1.access-key-id))
          KUBECONFIG_AWS_SECRET_ACCESS_KEY: ((aws-live-1.secret-access-key))
          KUBECONFIG_AWS_REGION: eu-west-2
          KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
          KUBECONFIG_S3_KEY: kubeconfig
          KUBECONTEXT: cloud-platform-live-0.k8s.integration.dsd.io
          KUBECONFIG: /tmp/kubeconfig
          PIPELINE_CLUSTER: cloud-platform-live-0.k8s.integration.dsd.io
          PIPELINE_STATE_BUCKET: moj-cp-k8s-investigation-environments-terraform
          TFSTATE_AWS_ACCESS_KEY_ID: ((aws-live-0.access-key-id))
          TFSTATE_AWS_REGION: eu-west-1
          TFSTATE_AWS_SECRET_ACCESS_KEY: ((aws-live-0.secret-access-key))
        run:
          path: /bin/sh
          args:
            - -ce
            - |
              # run script and then format output for slack notification
              cd /app; ./bin/orphaned_namespaces.rb | tee /app/check.txt
              ls
              pwd
        inputs:
        outputs:
          - name: app
  on_success:
    do:
    - put: slack-alert
      params:
        channel: '#cloud-platform-notify'
        text_file: /app/check.txt
  on_failure:
    put: slack-alert
    params:
      channel: '#cloud-platform-notify'
      attachments:
        - color: "danger"
          fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
          title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
          title_link: 'https://concourse.apps.live-1.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
          footer: concourse.apps.live-1.cloud-platform.service.justice.gov.uk
