slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#cloud-platform-notify'
  silent: true
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished deleting old, manually-created pods'
  title: 'Delete manually-created-pods'
  title_link: 'https://concourse.apps.manager.cloud-platform.service.justice.gov.uk/teams/main/pipelines/delete-manually-created-pods'
  footer: concourse.apps.manager.cloud-platform.service.justice.gov.uk
resources:
- name: cloud-platform-environments-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-environments.git
    branch: master
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: 1.9
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-day
  type: time
  source:
    interval: 24h

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

groups:
- name: live-1
  jobs: [delete-manually-created-pods-live-1]

jobs:
  - name: delete-manually-created-pods-live-1
    serial: true
    plan:
      - aggregate:
        - get: every-day
          trigger: true
        - get: cloud-platform-environments-repo
        - get: tools-image
      - task: run-script
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            PIPELINE_CLUSTER: concourse.apps.manager.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                aws s3 cp s3://cloud-platform-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                bundle install --without development test
                ./bin/delete_manually_created_pods.rb

        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
