slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#lower-priority-alarms'
  silent: true
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.cloud-platform.service.justice.gov.uk

resources:
- name: cloud-platform-environments-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-environments.git
    branch: main
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
- name: pipeline-tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: "1.25"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: orphaned-statefiles-reporter-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-orphaned-terraform-statefiles
    tag: "1.3"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-day
  type: time
  source:
    interval: 24h
- name: every-120m
  type: time
  source:
    interval: 120m

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
- name: hoodaw
  jobs:
    - hoodaw-namespace-usage
    - hoodaw-orphaned-statefiles

jobs:
  - name: hoodaw-namespace-usage
    serial: true
    plan:
      - in_parallel:
        - get: every-120m
          trigger: true
        - get: cloud-platform-environments-repo
          trigger: false
        - get: pipeline-tools-image
      - task: post-namespace-usage-data
        image: pipeline-tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            HOODAW_HOST: ((hoodaw-creds.hostname))
            HOODAW_API_KEY: ((hoodaw-creds.api_key))
            PIPELINE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                (
                  aws s3 cp s3://cloud-platform-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                )
                kubectl config use-context ${PIPELINE_CLUSTER}
                ./bin/post_namespace_usage_data.sh
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS

  - name: hoodaw-orphaned-statefiles
    serial: true
    plan:
      - in_parallel:
        - get: every-day
          trigger: true
        - get: orphaned-statefiles-reporter-image
      - task: post-data
        image: orphaned-statefiles-reporter-image
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            AWS_REGION: "eu-west-2"
            KOPS_STATE_STORE: s3://cloud-platform-kops-state
            TF_STATE_BUCKET_REGION: "eu-west-1"
            TF_STATE_BUCKET_AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            TF_STATE_BUCKET_AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            HOODAW_HOST: https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
            HOODAW_API_KEY: ((hoodaw-creds.api_key))
          run:
            path: /bin/sh
            args:
              - -c
              - |-
                cd /app
                ./bin/post-data.sh
        on_failure:
          put: slack-alert
          params:
            <<: *SLACK_NOTIFICATION_DEFAULTS
            attachments:
              - color: "danger"
                <<: *SLACK_ATTACHMENTS_DEFAULTS
