slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
  channel: '#lower-priority-alarms'
  silent: true
slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
  fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
  title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
  footer: concourse.cloud-platform.service.justice.gov.uk

aws-credentials: &AWS_CREDENTIALS
  AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))

hoodaw-credentials: &HOODAW_CREDENTIALS
  HOODAW_HOST: ((hoodaw-creds.hostname))
  HOODAW_API_KEY: ((hoodaw-creds.api_key))

aws-plus-hoodaw: &AWS_AND_HOODAW_CREDENTIALS
  <<: *AWS_CREDENTIALS
  <<: *HOODAW_CREDENTIALS

kube-config: &KUBECONFIG_PARAMS
  KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
  KUBECONFIG_S3_KEY: kubeconfig
  KUBECONFIG: /tmp/kubeconfig

resources:
- name: cloud-platform-environments-repo
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-environments.git
    branch: main
    git_crypt_key: ((cloud-platform-environments-git-crypt.key))
- name: orphaned-namespace-checker-image
  type: docker-image
  source:
    repository: registry.hub.docker.com/ministryofjustice/orphaned-namespace-checker
    tag: "2.25"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: cost-calculator-image
  type: docker-image
  source:
    repository: registry.hub.docker.com/ministryofjustice/cloud-platform-cost-calculator
    tag: "2.1"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: orphaned-resources-reporter-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-report-orphaned-resources
    tag: "1.10"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: dashboard-reporter-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-how-out-of-date-are-we-reporter
    tag: "2.13"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: hoodaw-updater-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-how-out-of-date-are-we-updater
    tag: "2.27"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: pipeline-tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: "1.25"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: orphaned-statefiles-reporter-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-orphaned-terraform-statefiles
    tag: "1.3"
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/((slack-hook-id))
- name: every-hour
  type: time
  source:
    interval: 60m
- name: every-6-hours
  type: time
  source:
    interval: 6h
- name: every-12-hours
  type: time
  source:
    interval: 12h
- name: every-day
  type: time
  source:
    interval: 24h
- name: every-120m
  type: time
  source:
    interval: 120m
- name: every-24-hours
  type: time
  source:
    interval: 24h

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
    username: ((ministryofjustice-dockerhub.dockerhub_username))
    password: ((ministryofjustice-dockerhub.dockerhub_password))

groups:
- name: hoodaw
  jobs:
    - hoodaw-dashboard-reporter

jobs:
  - name: hoodaw-dashboard-reporter
    serial: true
    plan:
      - in_parallel:
        - get: every-24-hours
          trigger: true
        - get: dashboard-reporter-image
      - task: generate-report
        image: dashboard-reporter-image
        config:
          platform: linux
          outputs:
            - name: report
          params:
            DASHBOARD_URL: ((hoodaw-creds.hostname))/dashboard
            OUTPUT_FILE: report/action_items
          run:
            path: /app/report.rb
        on_failure:
          put: slack-alert
          params:
            channel: '#cloud-platform'
            text_file: report/action_items
            attachments:
              - color: "warning"
                title: 'How out of date are we - action required:'
                title_link: ((hoodaw-creds.hostname))/dashboard
                footer: ((hoodaw-creds.hostname))
