resources:
- name: updater-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-how-out-of-date-are-we-updater
    tag: 1.2
- name: every-24-hours
  type: time
  source:
    interval: 24h


jobs:
  - name: how-out-of-date-are-we
    serial: true
    plan:
      - in_parallel:
        - get: every-24-hours
          trigger: true
        - get: updater-image
      - task: how-out-of-date-are-we
        image: updater-image
        config:
          platform: linux
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG_S3_BUCKET: cloud-platform-concourse-kubeconfig
            KUBECONFIG_S3_KEY: kubeconfig
            KUBECONFIG: /tmp/kubeconfig
            KUBE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
            DATA_URL: https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
            GITHUB_TOKEN: ((how-out-of-date-are-we.how-out-of-date-are-we-github-token))
          run:
            path: /app/update.sh
