resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: cloud-platform-environments-live-1-pull-requests
  type: pull-request
  check_every: 1m
  source:
    repository: ministryofjustice/cloud-platform-environments
    access_token: ((cloud-platform-environments-pr-git-access-token))
    paths:
    - namespaces/live-1.cloud-platform.service.justice.gov.uk
- name: tools-image
  type: docker-image
  source:
    repository: registry.hub.docker.com/ministryofjustice/cloud-platform-tools
    tag: 1.15

groups:
- name: live-1
  jobs: [plan-live-1]

jobs:
  - name: plan-live-1
    serial: true
    plan:
      - get: cloud-platform-environments-live-1-pull-requests
        trigger: true
        version: every
      - put: cloud-platform-environments-live-1-pull-requests
        params:
          path: cloud-platform-environments-live-1-pull-requests
          status: pending
      - get: tools-image
      - task: plan-environments
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: cloud-platform-environments-live-1-pull-requests
          params:
            AWS_ACCESS_KEY_ID: ((aws-creds.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-creds.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            TF_PLUGIN_CACHE_DIR: /tmp/terraform-plugin-cache
            PINGDOM_USER: ((cloud-platform-environments-pingdom.pingdom_user))
            PINGDOM_PASSWORD: ((cloud-platform-environments-pingdom.pingdom_password))
            PINGDOM_API_KEY: ((cloud-platform-environments-pingdom.pingdom_api_key))
            # the variables prefixed with PIPELINE_ are used by the plan script
            PIPELINE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
            PIPELINE_STATE_BUCKET: cloud-platform-terraform-state
            PIPELINE_STATE_KEY_PREFIX: "cloud-platform-environments/"
            PIPELINE_STATE_REGION: "eu-west-1"
            PIPELINE_TERRAFORM_STATE_LOCK_TABLE: "cloud-platform-environments-terraform-lock"
            TF_VAR_cluster_name: "live-1"
            TF_VAR_cluster_state_bucket: cloud-platform-terraform-state
            TF_VAR_concourse_url: "https://concourse.cloud-platform.service.justice.gov.uk"
            TF_VAR_concourse_basic_auth_username: ((concourse-basic-auth.username))
            TF_VAR_concourse_basic_auth_password: ((concourse-basic-auth.password))
            TF_VAR_cluster_state_key: "cloud-platform/live-1/terraform.tfstate"
          run:
            path: /bin/sh
            dir: cloud-platform-environments-live-1-pull-requests
            args:
              - -c
              - |
                mkdir -p "${TF_PLUGIN_CACHE_DIR}"
                (
                  aws s3 cp s3://cloud-platform-concourse-kubeconfig/kubeconfig /tmp/kubeconfig
                )
                export branch_head_sha=$(cat .git/resource/metadata.json | jq -r '.[] | select(.name == "head_sha") | .value')
                export master_base_sha=$(cat .git/resource/metadata.json | jq -r '.[] | select(.name == "base_sha") | .value')
                bundle install --without development test
                ./bin/plan
        on_failure:
            put: cloud-platform-environments-live-1-pull-requests
            params:
              path: cloud-platform-environments-live-1-pull-requests
              status: failure
        on_success:
            put: cloud-platform-environments-live-1-pull-requests
            params:
              path: cloud-platform-environments-live-1-pull-requests
              status: success
